### ISSUE TITLE
Method for ignoring a local server asset or file 

### ISSUE THREAD

**Issue by jasonbarone** [ProperJS/Router#4]
Would be useful to have some Router logic that determines whether a link is a local server asset or file, such as a link to a PDF or ZIP file located on the same domain.

**Comment by kitajchuk** [comment]
@jasonbarone - This commit seems a viable fix for this: a8198592ebea28563dff978f530237ace0b52dd2. Go ahead and test it out. If you're using `PageController`, you'll want to just trash that node_module and re-install it to pull the latest Router version into it - `0.2.6`.

**Comment by jasonbarone** [comment]
Thanks looks like this works great so far!

**Comment by kitajchuk** [comment]
@jasonbarone I've pushed some updates that make this solid. I ran into some issues with it myself since I had only tested on my localhost. Once I got it on a domain with a `.com` it was breaking. Latest version of Router is 0.3.3. PageController had some updates as well, v0.3.11 now, so an `npm update` on that should pull in all the latest modules for that. If that doesn't work, `rm -rf node_modules/properjs-pagecontroller && npm install properjs-pagecontroller`.
